"""Add medical history fields to patient profile

Revision ID: 60bf3db519d2
Revises: 
Create Date: 2026-08-10 12:53:39.115760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60bf3db519d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_doctors_id'), 'doctors', ['id'], unique=False)
    op.add_column('patients', sa.Column('chronic_conditions', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('past_surgeries', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('allergies', sa.Text(), nullable=True))
    op.drop_index(op.f('username'), table_name='staff')
    op.create_index(op.f('ix_staff_id'), 'staff', ['id'], unique=False)
    op.create_index(op.f('ix_staff_username'), 'staff', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_username'), table_name='staff')
    op.drop_index(op.f('ix_staff_id'), table_name='staff')
    op.create_index(op.f('username'), 'staff', ['username'], unique=True)
    op.drop_column('patients', 'allergies')
    op.drop_column('patients', 'past_surgeries')
    op.drop_column('patients', 'chronic_conditions')
    op.drop_index(op.f('ix_doctors_id'), table_name='doctors')
    # ### end Alembic commands ###
